### ISSUE TITLE
Fix with the new base

### ISSUE THREAD

**Issue by fakedrake** [srijs/coholos#3]
Could you update for `base >= 4.9.1.0`? Thanks

**Comment by srijs** [comment]
Hi! I'll take a look today.

**Comment by fakedrake** [comment]
Thanks

**Comment by srijs** [comment]
Apologies for the delay. `hwsl2` version 0.4.0.1 should now build with GHC 7.10 as well as 8.0 and 8.2 (build matrix here: https://matrix.hackage.haskell.org/package/hwsl2).

Please let me know if you run into any other problems!

**Comment by fakedrake** [comment]
Thanks
Sam Rijs <notifications@github.com> writes:

> Apologies for the delay. `hwsl2` version 0.4.0.1 should now build with GHC 7.10 as well as 8.0. Please let me know if you run into any other problems!
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/srijs/hwsl2-haskell/issues/3#issuecomment-341677698

-- 
Chris Perivolaropoulos
University of Edinburgh
School of Informatics - IF-2.05

Web: fakedrake.github.io
Mail: c.perivol@ed.ac.uk
